language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  api_key:
    secure: foKNxPVTNr51O2IH2mqZ8vo6YuXjr0hmIPjNAhxRXh5aGd/MRmc7YeWt9ETPm3felC61oB356z40K3y1Ysf05BOOpeeECIn1JXTHqOUlpTB7bF9THVGN2LMhWFf13NcHvn20xQauENaJgE/t9iLPkLcBmN4pCVKiHq1Fl5D9+wewqaDRo2iRhpi0b5femfYJ2YR2yiqutOGv1Ta+EE+W3GHdvMDJryhleK/jRBtsl11xt6cr9kSBIEQafkfMmYmrTGOxkydKM60x5vbvrs+FIk0ZwIZSSNbX106H8hlRl7VGn4ZH68YXi1LWN/Cj2pKqsltfPsdFGgeC8maVkYeGnhsJ+dbNYU+eNhvc/xMTkK8MpbVk5BigLH+6/UxYlPTbaN4vKhFKe4WbQ2XjzEqMlaP8TiUU2FN+2Cgf2AH0hjDwkpVoCfkOhaeXOYai39AxHa4YVCYtX6DF/L3S/XNj8Fw7B/nIpErXjzSshBkiNd0+RcyaVBES4Y8KtEB1eHTaYlFT1p8KUovfJWK4DFpRB79Yvq5+LjHxoMBn+hWtorn4D3m82dGrqKMy+38aTmFDDRH/z1ggxkZqQfvWcb+gybr3JHv1r2I5v5GxmqrH/VPfyBUiy6K//CcdEWAO3PATzDymlqJfvmk8NaVeyiMVUmoLe161qMHJ9+zhEzMGhsE=
