language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devops4labsgiancarlo
deploy:
  api_key:
    secure: DN0xgxhcyQc4uwS8Vn7OuI6ddX5XoElS5n+HNNHYn0ZCUHRg/mdLYFevLNU8fyPCwf/xWlbFY/rqddIAKa58nq76UkSkkx7dydu8rTSZxSeIyN1D9HnHUwFzUJkbOVEmEgwdLIYgFW5t1TiYW8dBekCChQjMY3Ihy6kNPeE+Rlovtp6a4cj0OuyS1TzPraC5GzsoyGx+TbUP9geCEjOrGG4ue25wv8tVAWagyheBBod03Sr3Z+Unch0Gcv8vXJxMj+88yd+oAvl2Z9K2UrdTYlr9KECENJyBMEodfnpnh8Rl4rNsPF4lYSCCJTy4yToP0/uLXnABHPBz6kdDoiesCJ6Z9QTs638KD/OvObtuiZKHGER+fCGmSm/0dHKFlU9qsmFc6j1fJalyjGXhBva9URxg7Uf/AS0BIJTt3P18+Bw+0MJr17Yi0VVCvnc/HiJqr4u1Pou0JVj8fERsvIj+510Ir3DbLLSkmkCyswSzRCUDKFy/JTkiBuqY3JmeV2ZoQS0PF3c2A1/FhQc3hrtFBSD+HC+0CKET5SHKL70Ztkk1qCoXj97eZF7U25gQCIbbxhzMCcd+SS0ssOatbr9SbCZ3fNLw+wobxdOrloYjp8dWEU/5OMOA0PAxoLXyuZN9FjkkuS3PHUCX6kIXrDRv3QhUMdeoT8Z+LHbQfR29i7Q=
