language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  api_key:
    secure: Ssl9wzN29LLEeOU0zBFRVlD3usWxMJrLIWp3TgpFPL7NNAqXXFbGZFBChVhqncQnK87mFTiELRHT2yt5dtoY/Dob9/iYIPDfdZ0JufOaTFCoYX8x+vlpgcuh0UytpVbAlG/PLgGydKMaD/FmPSSMUUA71y8q6IsJWM7X+SpqI8z4ZVpRtNoee7DmYnsBKK8asPGPCLIJKwAP33sSmA+vFqq78FzviiH/Lvke4MTeAchVsLb6UcoBXV9twHBhSyD9jAQ7jcJALJ0atjaCi21NYOWuj1/7ZSfoE64Gtkm/1vYfbeysTBv+TDRZeQ0ka7GiBfRuA4OrYRpapC2HPBfhAXfxSCtRqRDtTmy6aXmBhtazw3xbDPWNmfAEx+5ljidPGLyW0Ny9Z1sWRiD8cLuBzbs74qi82IDsFJlPqmV3/5M3op8rcbWge0ARJ3OQ546JrY8YchITy+6RcmlDUxCqVqJuNOA/MxemwhDPk3fVC1LkSUuiG/Y85pI96cyay/ykPgDH3nTY1/srapHRIvxkxdKJjt5yy3lNSbZAEQU0eDdGm6+2wfcEpxf46UPbDuCYsj1ForWJp7rp55Jd60O+YmJ8ywJ5s6b1toCgEBhhxGiuTOPVOh+EbfGMqt2X2GbpE9gvEwsq8UsoMMrpl8NO0xu63fXHSRhkQY40tAXFrVU=
