language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  api_key:
    secure: VIh77L5FgqqJ/22h5ZSaI7blylATdkEXtKETrhB4htHVoaEGOt+UCCR+2Ddj1SB7GfG2uUfFtItnr3m0loBp88cRIcqo2GtpL95BEmiHmClo8oLBH5QYbtRBsCeEaSioZltlmHilArTAK1dB079YNYT+/cUv+kqqdu8WjHSHA/AX80tLo96F2vd5CXCj/QMvWLDAoqV1V1eM9ZTy5+qtvpFAn+yWEGDLGQM7mH1Y2sGw1L+SWpWqJJKRLSaOazxuyWCLdiokzRL0IObNGFNirLB7FrzFfDAPwlBGqmWb/Lo6HFOT+wuWeKwScgyzVLdamldGHyKQHpZst05aK+BGS21qszN7IjyuiB7V5AGI/Gnv37SpX2eS5nDNdtehNIFje4xIQ7CmcqnjpRzoW1RQI4tlT3vJk+aC5b6a2ZRVifL5D55J6eidVvTljT8sRvCdb6Nc+G4AYGdN9twzRjMhLh8r0C4QfbrlOhSLwvC6HFI5mfpISKnZIuq/CR3rSgILYzMk8ePkl+BzRqGmfMBYpiW+hD087IWSXm2eE+EWC77t8xowUuyyouZV1nfMvNhABccMgakqB4BDkR3pYoX+Z8d2jv02lsrLc2IyeHkH41EtYPGPupTjwTD16O1/C6Qqpvni0OMoc7vEAprgpHIUeBvnWf39k2bfSZ+vDWc/Bz4=
